---
- name: Install nginx
  hosts: webserver
  become: yes
  tasks:
    - name: Install nginx
      tags:
        - install
      dnf:
        name: nginx
        state: present

    - name: Remove
      tags:
        - remove
      dnf:
        name: nginx
        state: absent

