---
- name: Install nginx
  hosts: webserver
  become: yes
  tasks:
    - name: Install nginx
      dnf:
        name: nginx
        state: present

    - name: Enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Add http service to firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
     
    - name: To reload http 
      command: firewall-cmd --reload
         
       
        

